### PR TITLE
fix CommonJS support (fixes #242)

### LINKED ISSUE #242: CommonJS/browserify support?
As a relative newbie to the JS packaging world I could easily be wrong, but it seems to me like noty won't currently work with [browserify](http://browserify.org/) or any other compiler or loader, because it doesn't conform to CommonJS or AMD package standards.  However I found a commit in a fork which fixes this: https://github.com/Tol1/noty/commit/16380ede07dd8f8f4d0d82be8f0fff342ce651b2

I have asked @Tol1 to submit a pull request.  I think that it would only take [adding a single line to `package.json`](https://github.com/Tol1/noty/commit/16380ede07dd8f8f4d0d82be8f0fff342ce651b2#diff-3) to fix CommonJS support:

    "main": "js/noty/packaged/jquery.noty.packaged.js",

And in fact [`bower.json` already has this](https://github.com/needim/noty/blob/master/bower.json#L4) :-)

### PR DESCRIPTION
**Pull request by aspiers**
Example usage:

    require('noty');

    window.noty({ ... });

window is required if noty is being invoked from a required package.

### CODE REVIEW

**Comment by LoicMahieu** [comment]
+1

**Comment by LoicMahieu** [comment]
It's nice but not complete. `module.exports` is not filled with `noty`, so `require('noty') === undefined`.
I open a PR on aspiers/noty about this. https://github.com/aspiers/noty/pull/1

**Comment by aspiers** [comment]
@LoicMahieu Thanks very much! I don't know why I didn't think of that. I guess I'm still a Javascript newbie ;-)

**Comment by LoicMahieu** [comment]
@aspiers Ugly multi module wrapper are bad parts of javascript ecosystem (but necessary here indeed). Only remember The Good Parts ;)

**Comment by aspiers** [comment]
:)

**Pull request merged**
